name: MSBuild

on: push
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        mkdir x64/${{env.BUILD_CONFIGURATION}}/sid1
        mv t2-dc–disasm/sid1/sidbase.bin x64/${{env.BUILD_CONFIGURATION}}/sid1/sidbase.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: |
          x64/**/*.bin
          x64/**/*.exe
          x64/**/*.pdb
